export const CHANGE_MODE = "CHANGE_MODE";
export const UPDATE_SEARCH_FIELD = "UPDATE_SEARCH_FIELD";
export const SUMMONER_FOUND = "SUMMONER_FOUND";
export const SUMMONER_NOT_FOUND = "SUMMONER_NOT_FOUND";
export const SET_MATCH_HISTORY = "SET_MATCH_HISTORY";
